/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MealInput = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'date' : IDL.Text,
  'calories' : IDL.Nat,
  'mealName' : IDL.Text,
  'protein' : IDL.Nat,
});
export const Meal = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'date' : IDL.Text,
  'calories' : IDL.Nat,
  'timestamp' : IDL.Int,
  'mealName' : IDL.Text,
  'protein' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'completed' : IDL.Bool,
});
export const WorkoutInput = IDL.Record({
  'weight' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exerciseName' : IDL.Text,
});
export const Workout = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'timestamp' : IDL.Int,
  'exerciseName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'authorId' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : Timestamp,
  'postId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'followersCount' : IDL.Nat,
  'email' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'followingCount' : IDL.Nat,
  'isPublic' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'likeCount' : IDL.Nat,
  'authorId' : IDL.Text,
  'text' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'commentCount' : IDL.Nat,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'authorId' : IDL.Text,
  'text' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'lastMessageTime' : IDL.Int,
  'otherUsername' : IDL.Text,
  'otherUserId' : IDL.Text,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
});
export const FoodPreset = IDL.Record({
  'id' : IDL.Nat,
  'proteinPer100g' : IDL.Float64,
  'name' : IDL.Text,
  'carbsPer100g' : IDL.Float64,
  'fatPer100g' : IDL.Float64,
  'caloriesPer100g' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserGoals = IDL.Record({
  'weeklyMinWorkouts' : IDL.Nat,
  'dailyCalorieTarget' : IDL.Nat,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const MessageRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'timestamp' : IDL.Int,
  'previewText' : IDL.Text,
  'recipientId' : IDL.Text,
  'senderId' : IDL.Text,
});
export const MessageId = IDL.Text;
export const MessageReaction = IDL.Record({
  'userId' : IDL.Principal,
  'emoji' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
  'recipientId' : IDL.Text,
  'reactions' : IDL.Vec(MessageReaction),
  'senderId' : IDL.Text,
});
export const PersonalRecord = IDL.Record({
  'maxWeight' : IDL.Opt(IDL.Float64),
  'achievedAt' : Timestamp,
  'exerciseName' : IDL.Text,
  'maxReps' : IDL.Nat,
  'maxSets' : IDL.Nat,
});
export const WaterLog = IDL.Record({ 'date' : IDL.Text, 'amount' : IDL.Nat });
export const DayOfWeek = IDL.Nat;
export const WeeklyScheduleEntry = IDL.Record({
  'lastEditedTimestamp' : IDL.Opt(Timestamp),
  'lastEditedWeight' : IDL.Opt(IDL.Float64),
  'dayOfWeek' : DayOfWeek,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Opt(IDL.Float64),
  'exerciseName' : IDL.Text,
});
export const WorkoutStreak = IDL.Record({
  'lastWorkoutDate' : IDL.Opt(IDL.Text),
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const MealSuggestion = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'protein' : IDL.Float64,
});

export const idlService = IDL.Service({
  'acceptMessageRequest' : IDL.Func([IDL.Text], [], []),
  'addMeal' : IDL.Func([MealInput], [Meal], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text], [Task], []),
  'addWorkout' : IDL.Func([WorkoutInput], [Workout], []),
  'canMessageUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'clearScheduleDay' : IDL.Func([IDL.Nat], [], []),
  'createComment' : IDL.Func([IDL.Nat, IDL.Text], [Comment], []),
  'createOrGetProfile' : IDL.Func([], [UserProfile], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Post], []),
  'createStory' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Story], []),
  'declineMessageRequest' : IDL.Func([IDL.Text], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteConversation' : IDL.Func([IDL.Text], [], []),
  'deleteMeal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteWorkout' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'exportFitnessCSV' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'exportNutritionCSV' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'followUser' : IDL.Func([IDL.Text], [], []),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'getDailySummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'waterMl' : IDL.Nat,
          'totalCarbs' : IDL.Nat,
          'workoutCount' : IDL.Nat,
          'taskCompletionPct' : IDL.Float64,
          'totalFat' : IDL.Nat,
          'totalCalories' : IDL.Nat,
          'totalProtein' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'getFoodPreset' : IDL.Func([IDL.Nat], [IDL.Opt(FoodPreset)], ['query']),
  'getGoals' : IDL.Func([], [UserGoals], ['query']),
  'getMealsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Meal)], ['query']),
  'getMealsInRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Meal)],
      ['query'],
    ),
  'getMessageRequests' : IDL.Func([], [IDL.Vec(MessageRequest)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPersonalRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PersonalRecord)],
      ['query'],
    ),
  'getPersonalRecords' : IDL.Func([], [IDL.Vec(PersonalRecord)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getUserStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
  'getWaterForDate' : IDL.Func([IDL.Text], [WaterLog], ['query']),
  'getWeeklySchedule' : IDL.Func([], [IDL.Vec(WeeklyScheduleEntry)], ['query']),
  'getWeeklySummary' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'avgWaterPerDay' : IDL.Float64,
          'avgCaloriesPerDay' : IDL.Float64,
          'workoutsThisWeek' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getWorkoutStreak' : IDL.Func([], [WorkoutStreak], ['query']),
  'getWorkoutsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Workout)], ['query']),
  'getWorkoutsInRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Workout)],
      ['query'],
    ),
  'hasLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'listFoodPresets' : IDL.Func([], [IDL.Vec(FoodPreset)], ['query']),
  'logWater' : IDL.Func([IDL.Text, IDL.Nat], [WaterLog], []),
  'markMessageRead' : IDL.Func([IDL.Text], [], []),
  'removeReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveGoals' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveWeeklySchedule' : IDL.Func([IDL.Vec(WeeklyScheduleEntry)], [], []),
  'searchFoodPresets' : IDL.Func([IDL.Text], [IDL.Vec(FoodPreset)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
  'sendMessageRequest' : IDL.Func([IDL.Text, IDL.Text], [MessageRequest], []),
  'suggestMeals' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(MealSuggestion)],
      [],
    ),
  'toggleTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([IDL.Text], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [UserProfile],
      [],
    ),
  'updateProfilePhoto' : IDL.Func([IDL.Text], [], []),
  'updateScheduleEntry' : IDL.Func([WeeklyScheduleEntry], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MealInput = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'date' : IDL.Text,
    'calories' : IDL.Nat,
    'mealName' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const Meal = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'date' : IDL.Text,
    'calories' : IDL.Nat,
    'timestamp' : IDL.Int,
    'mealName' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const WorkoutInput = IDL.Record({
    'weight' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exerciseName' : IDL.Text,
  });
  const Workout = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'timestamp' : IDL.Int,
    'exerciseName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'authorId' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : Timestamp,
    'postId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'followersCount' : IDL.Nat,
    'email' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'followingCount' : IDL.Nat,
    'isPublic' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'likeCount' : IDL.Nat,
    'authorId' : IDL.Text,
    'text' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'commentCount' : IDL.Nat,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'authorId' : IDL.Text,
    'text' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'lastMessageTime' : IDL.Int,
    'otherUsername' : IDL.Text,
    'otherUserId' : IDL.Text,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
  });
  const FoodPreset = IDL.Record({
    'id' : IDL.Nat,
    'proteinPer100g' : IDL.Float64,
    'name' : IDL.Text,
    'carbsPer100g' : IDL.Float64,
    'fatPer100g' : IDL.Float64,
    'caloriesPer100g' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserGoals = IDL.Record({
    'weeklyMinWorkouts' : IDL.Nat,
    'dailyCalorieTarget' : IDL.Nat,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const MessageRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'timestamp' : IDL.Int,
    'previewText' : IDL.Text,
    'recipientId' : IDL.Text,
    'senderId' : IDL.Text,
  });
  const MessageId = IDL.Text;
  const MessageReaction = IDL.Record({
    'userId' : IDL.Principal,
    'emoji' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
    'recipientId' : IDL.Text,
    'reactions' : IDL.Vec(MessageReaction),
    'senderId' : IDL.Text,
  });
  const PersonalRecord = IDL.Record({
    'maxWeight' : IDL.Opt(IDL.Float64),
    'achievedAt' : Timestamp,
    'exerciseName' : IDL.Text,
    'maxReps' : IDL.Nat,
    'maxSets' : IDL.Nat,
  });
  const WaterLog = IDL.Record({ 'date' : IDL.Text, 'amount' : IDL.Nat });
  const DayOfWeek = IDL.Nat;
  const WeeklyScheduleEntry = IDL.Record({
    'lastEditedTimestamp' : IDL.Opt(Timestamp),
    'lastEditedWeight' : IDL.Opt(IDL.Float64),
    'dayOfWeek' : DayOfWeek,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Opt(IDL.Float64),
    'exerciseName' : IDL.Text,
  });
  const WorkoutStreak = IDL.Record({
    'lastWorkoutDate' : IDL.Opt(IDL.Text),
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const MealSuggestion = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'protein' : IDL.Float64,
  });
  
  return IDL.Service({
    'acceptMessageRequest' : IDL.Func([IDL.Text], [], []),
    'addMeal' : IDL.Func([MealInput], [Meal], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTask' : IDL.Func([IDL.Text, IDL.Text], [Task], []),
    'addWorkout' : IDL.Func([WorkoutInput], [Workout], []),
    'canMessageUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'clearScheduleDay' : IDL.Func([IDL.Nat], [], []),
    'createComment' : IDL.Func([IDL.Nat, IDL.Text], [Comment], []),
    'createOrGetProfile' : IDL.Func([], [UserProfile], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Post], []),
    'createStory' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Story], []),
    'declineMessageRequest' : IDL.Func([IDL.Text], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteConversation' : IDL.Func([IDL.Text], [], []),
    'deleteMeal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteWorkout' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'exportFitnessCSV' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'exportNutritionCSV' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        ['query'],
      ),
    'followUser' : IDL.Func([IDL.Text], [], []),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getDailySummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'waterMl' : IDL.Nat,
            'totalCarbs' : IDL.Nat,
            'workoutCount' : IDL.Nat,
            'taskCompletionPct' : IDL.Float64,
            'totalFat' : IDL.Nat,
            'totalCalories' : IDL.Nat,
            'totalProtein' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'getFoodPreset' : IDL.Func([IDL.Nat], [IDL.Opt(FoodPreset)], ['query']),
    'getGoals' : IDL.Func([], [UserGoals], ['query']),
    'getMealsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Meal)], ['query']),
    'getMealsInRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Meal)],
        ['query'],
      ),
    'getMessageRequests' : IDL.Func([], [IDL.Vec(MessageRequest)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPersonalRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PersonalRecord)],
        ['query'],
      ),
    'getPersonalRecords' : IDL.Func([], [IDL.Vec(PersonalRecord)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getUserStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
    'getWaterForDate' : IDL.Func([IDL.Text], [WaterLog], ['query']),
    'getWeeklySchedule' : IDL.Func(
        [],
        [IDL.Vec(WeeklyScheduleEntry)],
        ['query'],
      ),
    'getWeeklySummary' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'avgWaterPerDay' : IDL.Float64,
            'avgCaloriesPerDay' : IDL.Float64,
            'workoutsThisWeek' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getWorkoutStreak' : IDL.Func([], [WorkoutStreak], ['query']),
    'getWorkoutsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Workout)], ['query']),
    'getWorkoutsInRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Workout)],
        ['query'],
      ),
    'hasLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'listFoodPresets' : IDL.Func([], [IDL.Vec(FoodPreset)], ['query']),
    'logWater' : IDL.Func([IDL.Text, IDL.Nat], [WaterLog], []),
    'markMessageRead' : IDL.Func([IDL.Text], [], []),
    'removeReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveGoals' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveWeeklySchedule' : IDL.Func([IDL.Vec(WeeklyScheduleEntry)], [], []),
    'searchFoodPresets' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FoodPreset)],
        ['query'],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
    'sendMessageRequest' : IDL.Func([IDL.Text, IDL.Text], [MessageRequest], []),
    'suggestMeals' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(MealSuggestion)],
        [],
      ),
    'toggleTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([IDL.Text], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [UserProfile],
        [],
      ),
    'updateProfilePhoto' : IDL.Func([IDL.Text], [], []),
    'updateScheduleEntry' : IDL.Func([WeeklyScheduleEntry], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };