/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'authorUsername' : string,
  'authorId' : string,
  'text' : string,
  'timestamp' : Timestamp,
  'postId' : bigint,
}
export interface ConversationSummary {
  'lastMessageTime' : bigint,
  'otherUsername' : string,
  'otherUserId' : string,
  'lastMessage' : string,
  'unreadCount' : bigint,
}
export type DayOfWeek = bigint;
export interface FoodPreset {
  'id' : bigint,
  'proteinPer100g' : number,
  'name' : string,
  'carbsPer100g' : number,
  'fatPer100g' : number,
  'caloriesPer100g' : bigint,
  'category' : string,
}
export interface Meal {
  'id' : bigint,
  'fat' : bigint,
  'carbs' : bigint,
  'date' : string,
  'calories' : bigint,
  'timestamp' : bigint,
  'mealName' : string,
  'protein' : bigint,
}
export interface MealInput {
  'fat' : bigint,
  'carbs' : bigint,
  'date' : string,
  'calories' : bigint,
  'mealName' : string,
  'protein' : bigint,
}
export interface MealSuggestion {
  'fat' : number,
  'carbs' : number,
  'calories' : number,
  'name' : string,
  'protein' : number,
}
export interface Message {
  'id' : MessageId,
  'text' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'recipientId' : string,
  'reactions' : Array<MessageReaction>,
  'senderId' : string,
}
export type MessageId = string;
export interface MessageReaction {
  'userId' : Principal,
  'emoji' : string,
  'timestamp' : bigint,
}
export interface MessageRequest {
  'id' : string,
  'status' : RequestStatus,
  'timestamp' : bigint,
  'previewText' : string,
  'recipientId' : string,
  'senderId' : string,
}
export interface PersonalRecord {
  'maxWeight' : [] | [number],
  'achievedAt' : Timestamp,
  'exerciseName' : string,
  'maxReps' : bigint,
  'maxSets' : bigint,
}
export interface Post {
  'id' : bigint,
  'authorUsername' : string,
  'likeCount' : bigint,
  'authorId' : string,
  'text' : string,
  'photoUrl' : [] | [string],
  'timestamp' : Timestamp,
  'commentCount' : bigint,
}
export type RequestStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface Story {
  'id' : bigint,
  'authorUsername' : string,
  'authorId' : string,
  'text' : [] | [string],
  'photoUrl' : string,
  'timestamp' : Timestamp,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'completed' : boolean,
}
export type Timestamp = bigint;
export interface UserGoals {
  'weeklyMinWorkouts' : bigint,
  'dailyCalorieTarget' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : [] | [string],
  'userId' : string,
  'followersCount' : bigint,
  'email' : [] | [string],
  'avatarUrl' : [] | [string],
  'followingCount' : bigint,
  'isPublic' : boolean,
  'phone' : [] | [string],
}
export interface WaterLog { 'date' : string, 'amount' : bigint }
export interface WeeklyScheduleEntry {
  'lastEditedTimestamp' : [] | [Timestamp],
  'lastEditedWeight' : [] | [number],
  'dayOfWeek' : DayOfWeek,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : [] | [number],
  'exerciseName' : string,
}
export interface Workout {
  'id' : bigint,
  'weight' : [] | [number],
  'date' : string,
  'reps' : bigint,
  'sets' : bigint,
  'timestamp' : bigint,
  'exerciseName' : string,
}
export interface WorkoutInput {
  'weight' : [] | [number],
  'date' : string,
  'reps' : bigint,
  'sets' : bigint,
  'exerciseName' : string,
}
export interface WorkoutStreak {
  'lastWorkoutDate' : [] | [string],
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface _SERVICE {
  'acceptMessageRequest' : ActorMethod<[string], undefined>,
  'addMeal' : ActorMethod<[MealInput], Meal>,
  'addReaction' : ActorMethod<[string, string], undefined>,
  'addTask' : ActorMethod<[string, string], Task>,
  'addWorkout' : ActorMethod<[WorkoutInput], Workout>,
  'canMessageUser' : ActorMethod<[string], boolean>,
  'clearScheduleDay' : ActorMethod<[bigint], undefined>,
  'createComment' : ActorMethod<[bigint, string], Comment>,
  'createOrGetProfile' : ActorMethod<[], UserProfile>,
  'createPost' : ActorMethod<[string, [] | [string]], Post>,
  'createStory' : ActorMethod<[string, [] | [string]], Story>,
  'declineMessageRequest' : ActorMethod<[string], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteConversation' : ActorMethod<[string], undefined>,
  'deleteMeal' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'deleteWorkout' : ActorMethod<[bigint], boolean>,
  'exportFitnessCSV' : ActorMethod<[string, string], string>,
  'exportNutritionCSV' : ActorMethod<[string, string], string>,
  'followUser' : ActorMethod<[string], undefined>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getDailySummary' : ActorMethod<
    [string],
    {
      'waterMl' : bigint,
      'totalCarbs' : bigint,
      'workoutCount' : bigint,
      'taskCompletionPct' : number,
      'totalFat' : bigint,
      'totalCalories' : bigint,
      'totalProtein' : bigint,
    }
  >,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getFollowers' : ActorMethod<[string], Array<UserProfile>>,
  'getFollowing' : ActorMethod<[string], Array<UserProfile>>,
  'getFoodPreset' : ActorMethod<[bigint], [] | [FoodPreset]>,
  'getGoals' : ActorMethod<[], UserGoals>,
  'getMealsForDate' : ActorMethod<[string], Array<Meal>>,
  'getMealsInRange' : ActorMethod<[string, string], Array<Meal>>,
  'getMessageRequests' : ActorMethod<[], Array<MessageRequest>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPersonalRecord' : ActorMethod<[string], [] | [PersonalRecord]>,
  'getPersonalRecords' : ActorMethod<[], Array<PersonalRecord>>,
  'getProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getStories' : ActorMethod<[], Array<Story>>,
  'getTasksForDate' : ActorMethod<[string], Array<Task>>,
  'getUserByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserPosts' : ActorMethod<[string], Array<Post>>,
  'getUserStories' : ActorMethod<[string], Array<Story>>,
  'getWaterForDate' : ActorMethod<[string], WaterLog>,
  'getWeeklySchedule' : ActorMethod<[], Array<WeeklyScheduleEntry>>,
  'getWeeklySummary' : ActorMethod<
    [string, string],
    {
      'avgWaterPerDay' : number,
      'avgCaloriesPerDay' : number,
      'workoutsThisWeek' : bigint,
    }
  >,
  'getWorkoutStreak' : ActorMethod<[], WorkoutStreak>,
  'getWorkoutsForDate' : ActorMethod<[string], Array<Workout>>,
  'getWorkoutsInRange' : ActorMethod<[string, string], Array<Workout>>,
  'hasLiked' : ActorMethod<[bigint], boolean>,
  'isFollowing' : ActorMethod<[string], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'listFoodPresets' : ActorMethod<[], Array<FoodPreset>>,
  'logWater' : ActorMethod<[string, bigint], WaterLog>,
  'markMessageRead' : ActorMethod<[string], undefined>,
  'removeReaction' : ActorMethod<[string, string], undefined>,
  'saveGoals' : ActorMethod<[bigint, bigint], undefined>,
  'saveWeeklySchedule' : ActorMethod<[Array<WeeklyScheduleEntry>], undefined>,
  'searchFoodPresets' : ActorMethod<[string], Array<FoodPreset>>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[string, string], Message>,
  'sendMessageRequest' : ActorMethod<[string, string], MessageRequest>,
  'suggestMeals' : ActorMethod<
    [number, number, number, number],
    Array<MealSuggestion>
  >,
  'toggleTask' : ActorMethod<[bigint], boolean>,
  'unfollowUser' : ActorMethod<[string], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
    ],
    UserProfile
  >,
  'updateProfilePhoto' : ActorMethod<[string], undefined>,
  'updateScheduleEntry' : ActorMethod<[WeeklyScheduleEntry], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];