/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkoutInput {
    weight?: number;
    date: string;
    reps: bigint;
    sets: bigint;
    exerciseName: string;
}
export interface PersonalRecord {
    maxWeight?: number;
    achievedAt: Timestamp;
    exerciseName: string;
    maxReps: bigint;
    maxSets: bigint;
}
export type Timestamp = bigint;
export interface Meal {
    id: bigint;
    fat: bigint;
    carbs: bigint;
    date: string;
    calories: bigint;
    timestamp: bigint;
    mealName: string;
    protein: bigint;
}
export interface Comment {
    id: bigint;
    authorUsername: string;
    authorId: string;
    text: string;
    timestamp: Timestamp;
    postId: bigint;
}
export interface Story {
    id: bigint;
    authorUsername: string;
    authorId: string;
    text?: string;
    photoUrl: string;
    timestamp: Timestamp;
}
export interface Task {
    id: bigint;
    title: string;
    date: string;
    completed: boolean;
}
export interface FoodPreset {
    id: bigint;
    proteinPer100g: number;
    name: string;
    carbsPer100g: number;
    fatPer100g: number;
    caloriesPer100g: bigint;
    category: string;
}
export interface MessageRequest {
    id: string;
    status: RequestStatus;
    timestamp: bigint;
    previewText: string;
    recipientId: string;
    senderId: string;
}
export interface WaterLog {
    date: string;
    amount: bigint;
}
export interface MessageReaction {
    userId: Principal;
    emoji: string;
    timestamp: bigint;
}
export interface WeeklyScheduleEntry {
    lastEditedTimestamp?: Timestamp;
    lastEditedWeight?: number;
    dayOfWeek: DayOfWeek;
    reps: bigint;
    sets: bigint;
    weightKg?: number;
    exerciseName: string;
}
export type MessageId = string;
export interface UserGoals {
    weeklyMinWorkouts: bigint;
    dailyCalorieTarget: bigint;
}
export interface Post {
    id: bigint;
    authorUsername: string;
    likeCount: bigint;
    authorId: string;
    text: string;
    photoUrl?: string;
    timestamp: Timestamp;
    commentCount: bigint;
}
export interface Message {
    id: MessageId;
    text: string;
    isRead: boolean;
    timestamp: bigint;
    recipientId: string;
    reactions: Array<MessageReaction>;
    senderId: string;
}
export interface WorkoutStreak {
    lastWorkoutDate?: string;
    longestStreak: bigint;
    currentStreak: bigint;
}
export interface MealSuggestion {
    fat: number;
    carbs: number;
    calories: number;
    name: string;
    protein: number;
}
export interface Workout {
    id: bigint;
    weight?: number;
    date: string;
    reps: bigint;
    sets: bigint;
    timestamp: bigint;
    exerciseName: string;
}
export interface MealInput {
    fat: bigint;
    carbs: bigint;
    date: string;
    calories: bigint;
    mealName: string;
    protein: bigint;
}
export type DayOfWeek = bigint;
export interface UserProfile {
    bio: string;
    username: string;
    displayName?: string;
    userId: string;
    followersCount: bigint;
    email?: string;
    avatarUrl?: string;
    followingCount: bigint;
    isPublic: boolean;
    phone?: string;
}
export interface ConversationSummary {
    lastMessageTime: bigint;
    otherUsername: string;
    otherUserId: string;
    lastMessage: string;
    unreadCount: bigint;
}
export enum RequestStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export interface backendInterface {
    acceptMessageRequest(requestId: string): Promise<void>;
    addMeal(entry: MealInput): Promise<Meal>;
    addReaction(messageId: string, emoji: string): Promise<void>;
    addTask(date: string, title: string): Promise<Task>;
    addWorkout(entry: WorkoutInput): Promise<Workout>;
    canMessageUser(targetUserId: string): Promise<boolean>;
    clearScheduleDay(dayOfWeek: bigint): Promise<void>;
    createComment(postId: bigint, text: string): Promise<Comment>;
    createOrGetProfile(): Promise<UserProfile>;
    createPost(text: string, photoUrl: string | null): Promise<Post>;
    createStory(photoUrl: string, text: string | null): Promise<Story>;
    declineMessageRequest(requestId: string): Promise<void>;
    deleteComment(commentId: bigint): Promise<void>;
    deleteConversation(otherUserId: string): Promise<void>;
    deleteMeal(id: bigint): Promise<boolean>;
    deletePost(postId: bigint): Promise<void>;
    deleteStory(storyId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<boolean>;
    deleteWorkout(id: bigint): Promise<boolean>;
    exportFitnessCSV(startDate: string, endDate: string): Promise<string>;
    exportNutritionCSV(startDate: string, endDate: string): Promise<string>;
    followUser(targetId: string): Promise<void>;
    getComments(postId: bigint): Promise<Array<Comment>>;
    getConversations(): Promise<Array<ConversationSummary>>;
    getDailySummary(date: string): Promise<{
        waterMl: bigint;
        totalCarbs: bigint;
        workoutCount: bigint;
        taskCompletionPct: number;
        totalFat: bigint;
        totalCalories: bigint;
        totalProtein: bigint;
    }>;
    getFeed(): Promise<Array<Post>>;
    getFollowers(userId: string): Promise<Array<UserProfile>>;
    getFollowing(userId: string): Promise<Array<UserProfile>>;
    getFoodPreset(id: bigint): Promise<FoodPreset | null>;
    getGoals(): Promise<UserGoals>;
    getMealsForDate(date: string): Promise<Array<Meal>>;
    getMealsInRange(startDate: string, endDate: string): Promise<Array<Meal>>;
    getMessageRequests(): Promise<Array<MessageRequest>>;
    getMessages(otherUserId: string): Promise<Array<Message>>;
    getMyProfile(): Promise<UserProfile | null>;
    getPersonalRecord(exerciseName: string): Promise<PersonalRecord | null>;
    getPersonalRecords(): Promise<Array<PersonalRecord>>;
    getProfile(userId: string): Promise<UserProfile | null>;
    getStories(): Promise<Array<Story>>;
    getTasksForDate(date: string): Promise<Array<Task>>;
    getUserByUsername(username: string): Promise<UserProfile | null>;
    getUserPosts(userId: string): Promise<Array<Post>>;
    getUserStories(userId: string): Promise<Array<Story>>;
    getWaterForDate(date: string): Promise<WaterLog>;
    getWeeklySchedule(): Promise<Array<WeeklyScheduleEntry>>;
    getWeeklySummary(startDate: string, endDate: string): Promise<{
        avgWaterPerDay: number;
        avgCaloriesPerDay: number;
        workoutsThisWeek: bigint;
    }>;
    getWorkoutStreak(): Promise<WorkoutStreak>;
    getWorkoutsForDate(date: string): Promise<Array<Workout>>;
    getWorkoutsInRange(startDate: string, endDate: string): Promise<Array<Workout>>;
    hasLiked(postId: bigint): Promise<boolean>;
    isFollowing(targetId: string): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    listFoodPresets(): Promise<Array<FoodPreset>>;
    logWater(date: string, amount: bigint): Promise<WaterLog>;
    markMessageRead(messageId: string): Promise<void>;
    removeReaction(messageId: string, emoji: string): Promise<void>;
    saveGoals(dailyCalorieTarget: bigint, weeklyMinWorkouts: bigint): Promise<void>;
    saveWeeklySchedule(entries: Array<WeeklyScheduleEntry>): Promise<void>;
    searchFoodPresets(nameQuery: string): Promise<Array<FoodPreset>>;
    searchUsers(searchTerm: string): Promise<Array<UserProfile>>;
    sendMessage(recipientId: string, text: string): Promise<Message>;
    sendMessageRequest(recipientId: string, previewText: string): Promise<MessageRequest>;
    suggestMeals(remainingCalories: number, remainingProtein: number, remainingCarbs: number, remainingFat: number): Promise<Array<MealSuggestion>>;
    toggleTask(taskId: bigint): Promise<boolean>;
    unfollowUser(targetId: string): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    updateProfile(username: string | null, email: string | null, phone: string | null, bio: string | null, displayName: string | null, isPublic: boolean | null): Promise<UserProfile>;
    updateProfilePhoto(url: string): Promise<void>;
    updateScheduleEntry(entry: WeeklyScheduleEntry): Promise<boolean>;
}
import type { DayOfWeek as _DayOfWeek, FoodPreset as _FoodPreset, MessageRequest as _MessageRequest, PersonalRecord as _PersonalRecord, Post as _Post, RequestStatus as _RequestStatus, Story as _Story, Timestamp as _Timestamp, UserProfile as _UserProfile, WeeklyScheduleEntry as _WeeklyScheduleEntry, Workout as _Workout, WorkoutInput as _WorkoutInput, WorkoutStreak as _WorkoutStreak } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptMessageRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptMessageRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptMessageRequest(arg0);
            return result;
        }
    }
    async addMeal(arg0: MealInput): Promise<Meal> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeal(arg0);
            return result;
        }
    }
    async addReaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return result;
        }
    }
    async addTask(arg0: string, arg1: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1);
            return result;
        }
    }
    async addWorkout(arg0: WorkoutInput): Promise<Workout> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkout(to_candid_WorkoutInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Workout_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkout(to_candid_WorkoutInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Workout_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async canMessageUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canMessageUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canMessageUser(arg0);
            return result;
        }
    }
    async clearScheduleDay(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearScheduleDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearScheduleDay(arg0);
            return result;
        }
    }
    async createComment(arg0: bigint, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1);
            return result;
        }
    }
    async createOrGetProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrGetProfile();
                return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrGetProfile();
            return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string | null): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Post_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Post_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: string, arg1: string | null): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Story_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Story_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async declineMessageRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineMessageRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineMessageRequest(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteConversation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0);
            return result;
        }
    }
    async deleteMeal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeal(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteStory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStory(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteWorkout(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkout(arg0);
            return result;
        }
    }
    async exportFitnessCSV(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportFitnessCSV(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportFitnessCSV(arg0, arg1);
            return result;
        }
    }
    async exportNutritionCSV(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportNutritionCSV(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportNutritionCSV(arg0, arg1);
            return result;
        }
    }
    async followUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getDailySummary(arg0: string): Promise<{
        waterMl: bigint;
        totalCarbs: bigint;
        workoutCount: bigint;
        taskCompletionPct: number;
        totalFat: bigint;
        totalCalories: bigint;
        totalProtein: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0);
            return result;
        }
    }
    async getFeed(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowing(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodPreset(arg0: bigint): Promise<FoodPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodPreset(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodPreset(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoals(): Promise<UserGoals> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return result;
        }
    }
    async getMealsForDate(arg0: string): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealsForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealsForDate(arg0);
            return result;
        }
    }
    async getMealsInRange(arg0: string, arg1: string): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealsInRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealsInRange(arg0, arg1);
            return result;
        }
    }
    async getMessageRequests(): Promise<Array<MessageRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageRequests();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageRequests();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalRecord(arg0: string): Promise<PersonalRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalRecord(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalRecord(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalRecords(): Promise<Array<PersonalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalRecords();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalRecords();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStories();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStories();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForDate(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForDate(arg0);
            return result;
        }
    }
    async getUserByUsername(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPosts(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStories(arg0: string): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStories(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStories(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaterForDate(arg0: string): Promise<WaterLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaterForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaterForDate(arg0);
            return result;
        }
    }
    async getWeeklySchedule(): Promise<Array<WeeklyScheduleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySchedule();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySchedule();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklySummary(arg0: string, arg1: string): Promise<{
        avgWaterPerDay: number;
        avgCaloriesPerDay: number;
        workoutsThisWeek: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySummary(arg0, arg1);
            return result;
        }
    }
    async getWorkoutStreak(): Promise<WorkoutStreak> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutStreak();
                return from_candid_WorkoutStreak_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutStreak();
            return from_candid_WorkoutStreak_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutsForDate(arg0: string): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutsForDate(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutsForDate(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutsInRange(arg0: string, arg1: string): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutsInRange(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutsInRange(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasLiked(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLiked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLiked(arg0);
            return result;
        }
    }
    async isFollowing(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listFoodPresets(): Promise<Array<FoodPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFoodPresets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFoodPresets();
            return result;
        }
    }
    async logWater(arg0: string, arg1: bigint): Promise<WaterLog> {
        if (this.processError) {
            try {
                const result = await this.actor.logWater(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWater(arg0, arg1);
            return result;
        }
    }
    async markMessageRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async removeReaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0, arg1);
            return result;
        }
    }
    async saveGoals(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGoals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGoals(arg0, arg1);
            return result;
        }
    }
    async saveWeeklySchedule(arg0: Array<WeeklyScheduleEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWeeklySchedule(to_candid_vec_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWeeklySchedule(to_candid_vec_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchFoodPresets(arg0: string): Promise<Array<FoodPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoodPresets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoodPresets(arg0);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async sendMessageRequest(arg0: string, arg1: string): Promise<MessageRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageRequest(arg0, arg1);
                return from_candid_MessageRequest_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageRequest(arg0, arg1);
            return from_candid_MessageRequest_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async suggestMeals(arg0: number, arg1: number, arg2: number, arg3: number): Promise<Array<MealSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestMeals(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestMeals(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async toggleTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTask(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: boolean | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5));
                return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5));
            return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfilePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePhoto(arg0);
            return result;
        }
    }
    async updateScheduleEntry(arg0: WeeklyScheduleEntry): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduleEntry(to_candid_WeeklyScheduleEntry_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduleEntry(to_candid_WeeklyScheduleEntry_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_MessageRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRequest): MessageRequest {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PersonalRecord_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonalRecord): PersonalRecord {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyScheduleEntry_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyScheduleEntry): WeeklyScheduleEntry {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutStreak_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutStreak): WorkoutStreak {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Workout_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Workout): Workout {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodPreset]): FoodPreset | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonalRecord]): PersonalRecord | null {
    return value.length === 0 ? null : from_candid_PersonalRecord_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    authorUsername: string;
    likeCount: bigint;
    authorId: string;
    text: string;
    photoUrl: [] | [string];
    timestamp: _Timestamp;
    commentCount: bigint;
}): {
    id: bigint;
    authorUsername: string;
    likeCount: bigint;
    authorId: string;
    text: string;
    photoUrl?: string;
    timestamp: Timestamp;
    commentCount: bigint;
} {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        likeCount: value.likeCount,
        authorId: value.authorId,
        text: value.text,
        photoUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.photoUrl)),
        timestamp: value.timestamp,
        commentCount: value.commentCount
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    authorUsername: string;
    authorId: string;
    text: [] | [string];
    photoUrl: string;
    timestamp: _Timestamp;
}): {
    id: bigint;
    authorUsername: string;
    authorId: string;
    text?: string;
    photoUrl: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        authorId: value.authorId,
        text: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.text)),
        photoUrl: value.photoUrl,
        timestamp: value.timestamp
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RequestStatus;
    timestamp: bigint;
    previewText: string;
    recipientId: string;
    senderId: string;
}): {
    id: string;
    status: RequestStatus;
    timestamp: bigint;
    previewText: string;
    recipientId: string;
    senderId: string;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n20(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp,
        previewText: value.previewText,
        recipientId: value.recipientId,
        senderId: value.senderId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxWeight: [] | [number];
    achievedAt: _Timestamp;
    exerciseName: string;
    maxReps: bigint;
    maxSets: bigint;
}): {
    maxWeight?: number;
    achievedAt: Timestamp;
    exerciseName: string;
    maxReps: bigint;
    maxSets: bigint;
} {
    return {
        maxWeight: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.maxWeight)),
        achievedAt: value.achievedAt,
        exerciseName: value.exerciseName,
        maxReps: value.maxReps,
        maxSets: value.maxSets
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastEditedTimestamp: [] | [_Timestamp];
    lastEditedWeight: [] | [number];
    dayOfWeek: _DayOfWeek;
    reps: bigint;
    sets: bigint;
    weightKg: [] | [number];
    exerciseName: string;
}): {
    lastEditedTimestamp?: Timestamp;
    lastEditedWeight?: number;
    dayOfWeek: DayOfWeek;
    reps: bigint;
    sets: bigint;
    weightKg?: number;
    exerciseName: string;
} {
    return {
        lastEditedTimestamp: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.lastEditedTimestamp)),
        lastEditedWeight: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.lastEditedWeight)),
        dayOfWeek: value.dayOfWeek,
        reps: value.reps,
        sets: value.sets,
        weightKg: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.weightKg)),
        exerciseName: value.exerciseName
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastWorkoutDate: [] | [string];
    longestStreak: bigint;
    currentStreak: bigint;
}): {
    lastWorkoutDate?: string;
    longestStreak: bigint;
    currentStreak: bigint;
} {
    return {
        lastWorkoutDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lastWorkoutDate)),
        longestStreak: value.longestStreak,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: [] | [number];
    date: string;
    reps: bigint;
    sets: bigint;
    timestamp: bigint;
    exerciseName: string;
}): {
    id: bigint;
    weight?: number;
    date: string;
    reps: bigint;
    sets: bigint;
    timestamp: bigint;
    exerciseName: string;
} {
    return {
        id: value.id,
        weight: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.weight)),
        date: value.date,
        reps: value.reps,
        sets: value.sets,
        timestamp: value.timestamp,
        exerciseName: value.exerciseName
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: [] | [string];
    userId: string;
    followersCount: bigint;
    email: [] | [string];
    avatarUrl: [] | [string];
    followingCount: bigint;
    isPublic: boolean;
    phone: [] | [string];
}): {
    bio: string;
    username: string;
    displayName?: string;
    userId: string;
    followersCount: bigint;
    email?: string;
    avatarUrl?: string;
    followingCount: bigint;
    isPublic: boolean;
    phone?: string;
} {
    return {
        bio: value.bio,
        username: value.username,
        displayName: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.displayName)),
        userId: value.userId,
        followersCount: value.followersCount,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.avatarUrl)),
        followingCount: value.followingCount,
        isPublic: value.isPublic,
        phone: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "accepted" in value ? RequestStatus.accepted : "declined" in value ? RequestStatus.declined : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageRequest>): Array<MessageRequest> {
    return value.map((x)=>from_candid_MessageRequest_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersonalRecord>): Array<PersonalRecord> {
    return value.map((x)=>from_candid_PersonalRecord_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeeklyScheduleEntry>): Array<WeeklyScheduleEntry> {
    return value.map((x)=>from_candid_WeeklyScheduleEntry_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Workout>): Array<Workout> {
    return value.map((x)=>from_candid_Workout_n3(_uploadFile, _downloadFile, x));
}
function to_candid_WeeklyScheduleEntry_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeeklyScheduleEntry): _WeeklyScheduleEntry {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutInput): _WorkoutInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight?: number;
    date: string;
    reps: bigint;
    sets: bigint;
    exerciseName: string;
}): {
    weight: [] | [number];
    date: string;
    reps: bigint;
    sets: bigint;
    exerciseName: string;
} {
    return {
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        date: value.date,
        reps: value.reps,
        sets: value.sets,
        exerciseName: value.exerciseName
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastEditedTimestamp?: Timestamp;
    lastEditedWeight?: number;
    dayOfWeek: DayOfWeek;
    reps: bigint;
    sets: bigint;
    weightKg?: number;
    exerciseName: string;
}): {
    lastEditedTimestamp: [] | [_Timestamp];
    lastEditedWeight: [] | [number];
    dayOfWeek: _DayOfWeek;
    reps: bigint;
    sets: bigint;
    weightKg: [] | [number];
    exerciseName: string;
} {
    return {
        lastEditedTimestamp: value.lastEditedTimestamp ? candid_some(value.lastEditedTimestamp) : candid_none(),
        lastEditedWeight: value.lastEditedWeight ? candid_some(value.lastEditedWeight) : candid_none(),
        dayOfWeek: value.dayOfWeek,
        reps: value.reps,
        sets: value.sets,
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none(),
        exerciseName: value.exerciseName
    };
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WeeklyScheduleEntry>): Array<_WeeklyScheduleEntry> {
    return value.map((x)=>to_candid_WeeklyScheduleEntry_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
